<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\KitchenOrderingSystem.Shared\KitchenOrderingSystem.Shared.csproj" />
      <ProjectReference Include="..\Kitchen.Domain\Kitchen.Domain.csproj" />
    </ItemGroup>

</Project>
